src/CJansson/ViewModels/Blog/BlogListPostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CJansson.ViewModels.Blog
{
    public class BlogListPostViewModel
    {
        public string Name { get; set; }

        public string URLSegment { get; set; }

        public string Description { get; set; }

        public DateTime Created { get; set; }

        public DateTime Changed { get; set; }

        public DateTime Publish { get; set; }

        public IEnumerable<string> Tags { get; set; }

        public bool IsPublished => this.Publish < DateTime.Now;

        // implement?
        //public string Hash
        //{
        //    get
        //    {
        //        using (MD5 md5Hash = MD5.Create())
        //        {
        //            string values = string.Format("{0},{1},{2}", ID, URLSegment, Changed);
        //            byte[] data = md5Hash.ComputeHash(Encoding.UTF8.GetBytes(values));

        //            StringBuilder sBuilder = new StringBuilder();
        //            for (int i = 0; i < data.Length; i++)
        //                sBuilder.Append(data[i].ToString("x2"));

        //            return sBuilder.ToString();
        //        }
        //    }
        //}
    }
}

src/CJansson/ViewModels/Blog/BlogListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CJansson.ViewModels.Blog
{
    public class BlogListViewModel
    {
        public IEnumerable<BlogListPostViewModel> Posts { get; set; }

        public BlogListViewModel()
        {
            this.Posts = new List<BlogListPostViewModel>();
        }
    }
}

src/CJansson/ViewModels/Blog/BlogPostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CJansson.ViewModels.Blog
{
    public class BlogPostViewModel : BlogListPostViewModel
    {
        public string SplashImage { get; set; }

        public string MainBody { get; set; }
    }
}

src/CJansson/Controllers/BlogController.cs
using CJansson.Core.ActionResults;
using CJansson.Services;
using CJansson.ViewModels.Blog;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace CJansson.Controllers
{
    public class BlogController : Controller
    {
        private const int PAGE_SIZE = 10;
        private const int RSS_SIZE = 50;
        private const int TEN_MINUTES_IN_SECONDS = 10 * 60;

        private readonly IBlogService blogService;

        public BlogController(IBlogService blogService)
        {
            this.blogService = blogService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            BlogListViewModel model = new BlogListViewModel
            {
                Posts = blogService.GetPosts().OrderByDescending(p => p.Publish)
            };

            return View(model);
        }

        [HttpGet("blog/category/{category}")]
        public ActionResult Category(string category)
        {
            BlogListViewModel model = new BlogListViewModel();
            model.Posts = blogService.GetPosts(category).OrderByDescending(p => p.Publish);

            return View("Index", model);
        }

        [HttpGet("blog/feed.rss")]
        public ActionResult RSS()
        {
            IEnumerable<BlogListPostViewModel> posts = blogService.GetPosts().OrderByDescending(p => p.Publish);

            RssActionResult rss = new RssActionResult("Blog - cjansson.se", "The programming and me", Url.Action("Index"));
            foreach (BlogListPostViewModel post in posts)
                rss.AddItem(post.Name, Url.Action("Post", new { urlSegment = post.URLSegment }), post.Publish, post.Description);

            return rss;
        }

        [HttpGet("blog/category/{category}/feed.rss")]
        public ActionResult RSSCategory(string category)
        {
            IEnumerable<BlogListPostViewModel> posts = blogService.GetPosts(category).OrderByDescending(p => p.Publish);

            RssActionResult rss = new RssActionResult("Blog - cjansson.se", "The programming and me", Url.Action("Category", new { category }));
            foreach (BlogListPostViewModel post in posts)
                rss.AddItem(post.Name, Url.Action("Post", new { urlSegment = post.URLSegment }), post.Publish, post.Description);

            return rss;
        }

        [HttpGet]
        [Route("blog/post/{urlSegment}")]
        public IActionResult Post(string urlSegment, string secret = null)
        {
            BlogPostViewModel model = blogService.GetPost(urlSegment, secret);
            if (model == null)
                return NotFound();

            return View(model);
        }
    }
}

src/CJansson/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CJansson.Services;
using Microsoft.AspNetCore.Mvc;

namespace CJansson.Controllers
{
    public class FilesController : Controller
    {
        private readonly IBlogService blogService;

        public FilesController(IBlogService blogService)
        {
            this.blogService = blogService;
        }
        
        [HttpGet("files/{blogUrl}/image/{image}")]
        public IActionResult Image(string blogUrl, string image)
        {
            byte[] fileData = blogService.GetImage(blogUrl, image);
            if (fileData == null)
                return NotFound();

            string mime = "image/jpeg";
            if (image.EndsWith(".png"))
                mime = "image/png";

            FileContentResult fileResult = new FileContentResult(fileData, mime);
            fileResult.FileDownloadName = image;

            return fileResult;
        }
        
        [HttpGet("files/{blogUrl}/code/{code}")]
        public IActionResult Code(string blogUrl, string code)
        {
            Tuple<string, string> codeFile = blogService.GetCodeFile(blogUrl, code);
            if (codeFile == null)
                return NotFound();

            byte[] codeBytes = Encoding.UTF8.GetBytes(codeFile.Item2);
            FileContentResult fileResult = new FileContentResult(codeBytes, "application/octet-stream");
            fileResult.FileDownloadName = codeFile.Item1;

            return fileResult;
        }
    }
}

src/CJansson/Views/Blog/Index.cshtml
@model CJansson.ViewModels.Blog.BlogListViewModel

@{
    ViewBag.Title = "Blog";
}

@section header {
    <link rel="alternate" type="application/rss+xml" title="CJansson.se - Blog" href="@Context.Request.Scheme://@Context.Request.Host@(Context.Request.Path)feed.rss" />

    <meta name="description" content="A blog about my life in code">

    <meta property="og:site_name" content="CJansson.se" />
    <meta property="og:title" content="CJansson.se - Blog" />
    <meta property="og:url" content="@Context.Request.Scheme://@Context.Request.Host@Context.Request.Path" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="A blog about my life in code" />

    <meta property="og:image" content="@Context.Request.Scheme://@Context.Request.Host/images/background.jpg" />
    <meta property="og:image:secure_url" content="@Context.Request.Scheme://@Context.Request.Host/images/background.jpg" />
}

<div class="splash">
    <h2>Blog</h2>
</div>

<div class="container content">
    <section class="blog-list">
        <h2 class="sr-only">Blog</h2>

        @foreach (var blog in Model.Posts)
        {
            <article>
                <header>
                    <h2><a asp-action="Post" asp-route-urlSegment="@blog.URLSegment">@blog.Name</a></h2>
                    <time datetime="@blog.Publish.ToString("s")"><span class="day">@blog.Publish.Day</span><span class="month">@blog.Publish.ToString("MMM")</span><span class="year">@blog.Publish.Year</span></time>
                </header>

                <p>@blog.Description</p>

                <footer>
                    <div class="tags">
                        @foreach (var tag in blog.Tags)
                        {
                            <a asp-action="Category" asp-route-category="@tag">@tag</a>
                        }
                    </div>
                    <span class="share-btns" data-title="CJansson.se - @blog.Name" data-url="@Url.Action("Post", "Blog", new { urlSegment = blog.URLSegment }, Context.Request.Scheme)">
                        <a href="#" data-site="facebook">
                            <svg viewBox="0 0 67 67" xmlns="http://www.w3.org/2000/svg">
                                <path d="M28.765 50.32h6.744V33.997h4.497l.596-5.624H35.51l.006-2.816c0-1.466.14-2.253 2.244-2.253h2.812V17.68h-4.5c-5.405 0-7.307 2.73-7.307 7.317v3.377h-3.37V34h3.37v16.32zM3 4h60v60H3V4z" fill-rule="evenodd" clip-rule="evenodd" fill="#3A589B" />
                            </svg>
                        </a>

                        <a href="#" data-site="twitter">
                            <svg viewBox="0 0 67 67" xmlns="http://www.w3.org/2000/svg">
                                <path d="M37.167 22.283c-2.62.953-4.274 3.41-4.086 6.1l.065 1.04-1.048-.128c-3.813-.487-7.145-2.14-9.974-4.915l-1.383-1.377-.357 1.017c-.754 2.268-.272 4.66 1.3 6.27.837.89.648 1.018-.797.488-.503-.17-.943-.296-.985-.233-.144.15.358 2.076.756 2.84.545 1.06 1.655 2.097 2.87 2.71l1.028.488-1.215.02c-1.174 0-1.216.022-1.09.467.42 1.377 2.074 2.84 3.92 3.475l1.297.444-1.13.676c-1.677.975-3.647 1.525-5.617 1.568-.945.02-1.72.106-1.72.17 0 .21 2.557 1.397 4.044 1.863 4.463 1.377 9.765.784 13.746-1.567 2.83-1.673 5.657-5 6.978-8.22.713-1.715 1.425-4.85 1.425-6.354 0-.975.063-1.102 1.236-2.267.69-.68 1.34-1.42 1.465-1.633.21-.403.188-.403-.88-.044-1.78.637-2.033.552-1.152-.4.65-.68 1.425-1.908 1.425-2.27 0-.06-.315.043-.672.234-.377.212-1.215.53-1.844.72l-1.13.36-1.028-.7c-.566-.38-1.36-.804-1.78-.93-1.07-.296-2.705-.254-3.67.085zM3 4h60v60H3V4z" fill-rule="evenodd" clip-rule="evenodd" fill="#598DCA" />
                            </svg>
                        </a>

                        <a href="#" data-site="linkedin">
                            <svg viewBox="0 0 67 67" xmlns="http://www.w3.org/2000/svg">
                                <path d="M49.837 48.137V36.425c0-6.274-3.35-9.194-7.816-9.194-3.602 0-5.217 1.984-6.117 3.375V27.71h-6.79c.09 1.917 0 20.428 0 20.428h6.79v-11.41c0-.61.044-1.22.224-1.656.49-1.22 1.607-2.482 3.482-2.482 2.457 0 3.44 1.873 3.44 4.618v10.93h6.79zM21.96 24.922c2.366 0 3.84-1.57 3.84-3.53-.043-2.004-1.474-3.53-3.796-3.53s-3.84 1.526-3.84 3.53c0 1.96 1.473 3.53 3.752 3.53h.043zm3.394 23.215V27.71h-6.79v20.427h6.79zM3 4h60v60H3V4z" fill-rule="evenodd" clip-rule="evenodd" fill="#007AB9" />
                            </svg>
                        </a>
                    </span>
                </footer>
            </article>
        }
    </section>
</div>

src/CJansson/Views/Blog/Post.cshtml
@model CJansson.ViewModels.Blog.BlogPostViewModel

@{
    string splashImage = Url.Action("Image", "Files", new { blogUrl = Model.URLSegment, image = Model.SplashImage }, Context.Request.Scheme);

    ViewBag.Title = Model.Name;
    ViewBag.TitleBefore = true;

    if (Model.SplashImage != null)
    {
        ViewBag.SplashImage = splashImage;
    }
}

@section header{
    <link rel="alternate" type="application/rss+xml" title="CJansson.se - Blog" href="@(Url.Action("Index", "Blog", null, Context.Request.Scheme))feed.rss" />

    <meta name="description" content="@Model.Description">

    <meta property="og:site_name" content="CJansson.se" />
    <meta property="og:title" content="@Model.Name - CJansson.se" />
    <meta property="og:url" content="@Context.Request.Scheme://@Context.Request.Host@Context.Request.Path" />
    <meta property="og:type" content="article" />
    <meta property="og:description" content="@Model.Description" />

    <meta property="article:published_time" content="@Model.Publish.ToString("s")" />
    <meta property="article:tag" content="@string.Join(", ", Model.Tags)" />

    @if (Model.SplashImage != null)
    {
        <meta property="og:image" content="@splashImage" />
        <meta property="og:image:secure_url" content="@splashImage" />
    }
    else
    {
        <meta property="og:image" content="@Context.Request.Scheme://@Context.Request.Host/images/background.jpg" />
        <meta property="og:image:secure_url" content="@Context.Request.Scheme://@Context.Request.Host/images/background.jpg" />
    }
}

<div class="splash small">
    <h2>@Model.Name</h2>
</div>

<div class="container content">
    <div class="post-heading">
        <time datetime="@Model.Publish.ToString("s")">@Model.Publish.ToString("MMMM dd, yyyy")</time>

        @if (Model.Tags.Any())
        {
            <span class="tags">
                @foreach (var tag in Model.Tags)
                {
                    <span class="tag">@tag</span>
                }
            </span>
        }

        <span class="share-btns">
            <a href="#" data-site="facebook">
                <svg viewBox="0 0 67 67" xmlns="http://www.w3.org/2000/svg">
                    <path d="M28.765 50.32h6.744V33.997h4.497l.596-5.624H35.51l.006-2.816c0-1.466.14-2.253 2.244-2.253h2.812V17.68h-4.5c-5.405 0-7.307 2.73-7.307 7.317v3.377h-3.37V34h3.37v16.32zM3 4h60v60H3V4z" fill-rule="evenodd" clip-rule="evenodd" fill="#3A589B" />
                </svg>
            </a>

            <a href="#" data-site="twitter">
                <svg viewBox="0 0 67 67" xmlns="http://www.w3.org/2000/svg">
                    <path d="M37.167 22.283c-2.62.953-4.274 3.41-4.086 6.1l.065 1.04-1.048-.128c-3.813-.487-7.145-2.14-9.974-4.915l-1.383-1.377-.357 1.017c-.754 2.268-.272 4.66 1.3 6.27.837.89.648 1.018-.797.488-.503-.17-.943-.296-.985-.233-.144.15.358 2.076.756 2.84.545 1.06 1.655 2.097 2.87 2.71l1.028.488-1.215.02c-1.174 0-1.216.022-1.09.467.42 1.377 2.074 2.84 3.92 3.475l1.297.444-1.13.676c-1.677.975-3.647 1.525-5.617 1.568-.945.02-1.72.106-1.72.17 0 .21 2.557 1.397 4.044 1.863 4.463 1.377 9.765.784 13.746-1.567 2.83-1.673 5.657-5 6.978-8.22.713-1.715 1.425-4.85 1.425-6.354 0-.975.063-1.102 1.236-2.267.69-.68 1.34-1.42 1.465-1.633.21-.403.188-.403-.88-.044-1.78.637-2.033.552-1.152-.4.65-.68 1.425-1.908 1.425-2.27 0-.06-.315.043-.672.234-.377.212-1.215.53-1.844.72l-1.13.36-1.028-.7c-.566-.38-1.36-.804-1.78-.93-1.07-.296-2.705-.254-3.67.085zM3 4h60v60H3V4z" fill-rule="evenodd" clip-rule="evenodd" fill="#598DCA" />
                </svg>
            </a>

            <a href="#" data-site="linkedin">
                <svg viewBox="0 0 67 67" xmlns="http://www.w3.org/2000/svg">
                    <path d="M49.837 48.137V36.425c0-6.274-3.35-9.194-7.816-9.194-3.602 0-5.217 1.984-6.117 3.375V27.71h-6.79c.09 1.917 0 20.428 0 20.428h6.79v-11.41c0-.61.044-1.22.224-1.656.49-1.22 1.607-2.482 3.482-2.482 2.457 0 3.44 1.873 3.44 4.618v10.93h6.79zM21.96 24.922c2.366 0 3.84-1.57 3.84-3.53-.043-2.004-1.474-3.53-3.796-3.53s-3.84 1.526-3.84 3.53c0 1.96 1.473 3.53 3.752 3.53h.043zm3.394 23.215V27.71h-6.79v20.427h6.79zM3 4h60v60H3V4z" fill-rule="evenodd" clip-rule="evenodd" fill="#007AB9" />
                </svg>
            </a>
        </span>
    </div>

    @Html.Raw(Model.MainBody)
</div>