src/CJansson/Controllers/BlogController.cs
using CJansson.Core.ActionResults;
using CJansson.Services;
using CJansson.ViewModels.Blog;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace CJansson.Controllers
{
    public class BlogController : Controller
    {
        private const int PAGE_SIZE = 10;
        private const int RSS_SIZE = 50;
        private const int TEN_MINUTES_IN_SECONDS = 10 * 60;

        private readonly IBlogService blogService;

        public BlogController(IBlogService blogService)
        {
            this.blogService = blogService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            BlogListViewModel model = new BlogListViewModel
            {
                Posts = blogService.GetPosts().OrderByDescending(p => p.Publish)
            };

            return View(model);
        }

        [HttpGet("blog/category/{category}")]
        public ActionResult Category(string category)
        {
            BlogListViewModel model = new BlogListViewModel();
            model.Posts = blogService.GetPosts(category).OrderByDescending(p => p.Publish);

            return View("Index", model);
        }

        [HttpGet("blog/feed.rss")]
        public ActionResult RSS()
        {
            IEnumerable<BlogListPostViewModel> posts = blogService.GetPosts().OrderByDescending(p => p.Publish);

            RssActionResult rss = new RssActionResult("Blog - cjansson.se", "The programming and me", Url.Action("Index"));
            foreach (BlogListPostViewModel post in posts)
                rss.AddItem(post.Name, Url.Action("Post", new { urlSegment = post.URLSegment }), post.Publish, post.Description);

            return rss;
        }

        [HttpGet("blog/category/{category}/feed.rss")]
        public ActionResult RSSCategory(string category)
        {
            IEnumerable<BlogListPostViewModel> posts = blogService.GetPosts(category).OrderByDescending(p => p.Publish);

            RssActionResult rss = new RssActionResult("Blog - cjansson.se", "The programming and me", Url.Action("Category", new { category }));
            foreach (BlogListPostViewModel post in posts)
                rss.AddItem(post.Name, Url.Action("Post", new { urlSegment = post.URLSegment }), post.Publish, post.Description);

            return rss;
        }

        [HttpGet]
        [Route("blog/post/{urlSegment}")]
        public IActionResult Post(string urlSegment, string secret = null)
        {
            BlogPostViewModel model = blogService.GetPost(urlSegment, secret);
            if (model == null)
                return NotFound();

            return View(model);
        }
    }
}

src/CJansson/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CJansson.Services;
using CJansson.ViewModels.Projects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace CJansson.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly IGitHubService gitHubService;
        private readonly IConfiguration configuration;

        public ProjectsController(IGitHubService gitHubService, IConfiguration configuration)
        {
            this.gitHubService = gitHubService;
            this.configuration = configuration;
        }

        public async Task<IActionResult> Index()
        {
            var repos = await gitHubService.GetPublicRepos(configuration["GitHub:Username"]);
            var latestUpdated = repos.OrderByDescending(x => x.UpdatedAt).Take(3).ToList();
            var topStarred = repos.Where(x => !latestUpdated.Contains(x)).OrderByDescending(x => x.StargazersCount).Take(3).ToList();

            var model = new ProjectListViewModel
            {
                GitHubUser = configuration["GitHub:Username"],
                ReposFetchedAt = repos.FetchedAt,
                Repos = latestUpdated.Union(topStarred).ToList()
            };
            return View(model);
        }
    }
}

src/CJansson/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />

    @if (ViewBag.TitleBefore != null && ViewBag.TitleBefore)
    {
        <title>@ViewBag.Title - CJansson.se</title>
    }
    else
    {
        <title>CJansson.se - @ViewBag.Title</title>
    }

    @RenderSection("header", false)

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/prism.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/prism.custom.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/scss/site.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/bundle.min.css" />
    </environment>

    @if (ViewBag.SplashImage != null)
    {
        <style type="text/css">
            .splash {
                background-image: url('@ViewBag.SplashImage');
            }
        </style>
    }
</head>
<body>
    <header class="header">
        <div class="container clearfix">
            <div class="logo">
                <h1>
                    <a asp-controller="Home" asp-action="Index">C<span class="full">hristopher</span><span class="space"></span>J<span class="full">ansson</span></a>
                </h1>
                <span class="extra">System Developer</span>
            </div>

            <nav class="menu">
                <ul>
                    <li>
                        <a asp-controller="Blog" asp-action="Index">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1750 1792">
                                <path d="M1703 478q40 57 18 129l-275 906q-19 64-76.5 107.5T1247 1664H324q-77 0-148.5-53.5T76 1479q-24-67-2-127 0-4 3-27t4-37q1-8-3-21.5t-3-19.5q2-11 8-21t16.5-23.5T116 1179q23-38 45-91.5t30-91.5q3-10 .5-30t-.5-28q3-11 17-28t17-23q21-36 42-92t25-90q1-9-2.5-32t.5-28q4-13 22-30.5t22-22.5q19-26 42.5-84.5T404 411q1-8-3-25.5t-2-26.5q2-8 9-18t18-23 17-21q8-12 16.5-30.5t15-35 16-36 19.5-32 26.5-23.5 36-11.5T620 134l-1 3q38-9 51-9h761q74 0 114 56t18 130l-274 906q-36 119-71.5 153.5T1089 1408H220q-27 0-38 15-11 16-1 43 24 70 144 70h923q29 0 56-15.5t35-41.5l300-987q7-22 5-57 38 15 59 43zm-1064 2q-4 13 2 22.5t20 9.5h608q13 0 25.5-9.5T1311 480l21-64q4-13-2-22.5t-20-9.5H702q-13 0-25.5 9.5T660 416zm-83 256q-4 13 2 22.5t20 9.5h608q13 0 25.5-9.5T1228 736l21-64q4-13-2-22.5t-20-9.5H619q-13 0-25.5 9.5T577 672z" />
                            </svg>
                            <span>Blog</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Projects" asp-action="Index">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1700 1792">
                                <path d="M782 1078q-1 3-12.5-.5T738 1066l-20-9q-44-20-87-49-7-5-41-31.5T552 948q-67 103-134 181-81 95-105 110-4 2-19.5 4t-18.5 0q6-4 82-92 21-24 85.5-115T521 918q17-30 51-98.5t36-77.5q-8-1-110 33-8 2-27.5 7.5T436 792t-17 5q-2 2-2 10.5t-1 9.5q-5 10-31 15-23 7-47 0-18-4-28-21-4-6-5-23 6-2 24.5-5t29.5-6q58-16 105-32 100-35 102-35 10-2 43-19.5t44-21.5q9-3 21.5-8t14.5-5.5 6 .5q2 12-1 33 0 2-12.5 27T655 769.5 638 803q-25 50-77 131l64 28q12 6 74.5 32t67.5 28q4 1 10.5 25.5t4.5 30.5zM577 592q3 15-4 28-12 23-50 38-30 12-60 12-26-3-49-26-14-15-18-41l1-3q3 3 19.5 5t26.5 0 58-16q36-12 55-14 17 0 21 17zm698 129l63 227-139-42zM167 1521l694-232V257L167 490v1031zm1241-317l102 31-181-657-100-31-216 536 102 31 45-110 211 65zM905 242l573 184V46zm311 1323l158 13-54 160-40-66q-130 83-276 108-58 12-91 12h-84q-79 0-199.5-39T446 1668q-8-7-8-16 0-8 5-13.5t13-5.5q4 0 18 7.5t30.5 16.5 20.5 11q73 37 159.5 61.5T842 1754q95 0 167-14.5t157-50.5q15-7 30.5-15.5t34-19 28.5-16.5zm448-1079v1079l-774-246q-14 6-375 127.5T147 1568q-13 0-18-13 0-1-1-3V474q3-9 4-10 5-6 20-11 106-35 149-50V19l558 198q2 0 160.5-55t316-108.5T1497 0q20 0 20 21v418z" />
                            </svg>
                            <span>Projects</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Home" asp-action="Contact">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1610 1792">
                                <path d="M1536 1536q0 63-61.5 113.5t-164 81-225 46T832 1792t-253.5-15.5-225-46-164-81T128 1536q0-49 33-88.5t91-66.5 118-44.5 131-29.5q26-5 48 10.5t26 41.5q5 26-10.5 48t-41.5 26q-58 10-106 23.5t-76.5 25.5-48.5 23.5-27.5 19.5-8.5 12q3 11 27 26.5t73 33 114 32.5 160.5 25 201.5 10 201.5-10 160.5-25 114-33 73-33.5 27-27.5q-1-4-8.5-11t-27.5-19-48.5-23.5-76.5-25-106-23.5q-26-4-41.5-26t-10.5-48q4-26 26-41.5t48-10.5q71 12 131 29.5t118 44.5 91 66.5 33 88.5zm-384-896v384q0 26-19 45t-45 19h-64v384q0 26-19 45t-45 19H704q-26 0-45-19t-19-45v-384h-64q-26 0-45-19t-19-45V640q0-53 37.5-90.5T640 512h384q53 0 90.5 37.5T1152 640zm-96-384q0 93-65.5 158.5T832 480t-158.5-65.5T608 256t65.5-158.5T832 32t158.5 65.5T1056 256z" />
                            </svg>
                            <span>Contact</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>

    @RenderBody()

    <footer>
        cjansson.se &copy; @DateTime.Today.Year
    </footer>

    <environment include="Development">
        <script src="~/lib/prism.js" asp-append-version="true"></script>
        <script src="~/lib/prism.custom.js" asp-append-version="true"></script>
        <script src="~/ts/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/bundle.min.js"></script>
        <script async src="https://analytics.trembon.se/script.js" data-website-id="93a2e580-bbd7-42e2-bc68-a09e4ecd28c8"></script>
    </environment>
</body>
</html>